// Generated by CoffeeScript 1.7.1
(function() {
  var fetchData, onFetchError, populateTables;

  $(function() {
    return $('#gimme').on('click', fetchData);
  });

  fetchData = function() {
    return jQuery.ajax("gsoc2014.json", {
      'async': true,
      'data': {
        'fmt': 'json',
        'limit': 2000,
        'idx': 0
      },
      'success': populateTables,
      'timeout': 30000,
      'crossDomain': true,
      'statusCode': {
        403: onFetchError
      },
      'error': onFetchError
    });
  };

  onFetchError = function(jqXHR, textStatus, errorThrown) {
    var errorMessage, now, tableWrapper;
    tableWrapper = $('#gsocTableWrapper');
    now = (new Date(Date.now())).toTimeString();
    errorMessage = $("<p><strong>No data available yet. Last check on " + now + ".</strong></p>");
    tableWrapper.html(errorMessage);
    return setTimeout(function() {
      return fetchData();
    }, 10000);
  };

  populateTables = function(data, status, jqXHR) {
    var columns, entries, entry, newHeader, newRow, table, tableWrapper, _i, _len, _results;
    console.debug(status);
    tableWrapper = $('#gsocTableWrapper');
    table = $('<table></table>');
    tableWrapper.html(table);
    newHeader = $('<tr><th>Mentors</th><th>Organization</th><th>Student</th><th>Title</th></tr>');
    table.append(newHeader);
    entries = data.data[""];
    _results = [];
    for (_i = 0, _len = entries.length; _i < _len; _i++) {
      entry = entries[_i];
      columns = entry['columns'];
      newRow = $('<tr></tr>');
      newRow.append("<td>" + columns['mentors'] + "</td>");
      newRow.append("<td>" + columns['organization'] + "</td>");
      newRow.append("<td>" + columns['student'] + "</td>");
      newRow.append("<td>" + columns['title'] + "</td>");
      _results.push(table.append(newRow));
    }
    return _results;
  };

}).call(this);
